### PR TITLE
href should be a protocol-relative reference

### PR DESCRIPTION
**Pull request by da2x**

### CODE REVIEW

**Comment by andydavies** [comment]
Can you explain a bit more why you think it needs to be relative?

Interestingly the [Resource Hints](https://www.w3.org/TR/resource-hints/) spec also uses a protocol relative reference for dns-prefetch

```
<link rel="dns-prefetch" href="//example.com">
```

But as the element is only making a DNS request so won't create a connection (which is where the protocol matters) I don't think it should be there.

Happy to have my 'mind changed' though.

**Comment by da2x** [comment]
I [left a comment](https://andydavies.me/blog/2013/10/22/how-the-browser-pre-loader-makes-pages-load-faster/#comment-4694924900) on one of your blog posts that explains it.

**Comment by da2x** [comment]
`<link href="duck">` resolves to `<base-url>/duck`.

`<link href="//duck">` resolves to `<base-url-scheme>://duck`.

**Comment by andydavies** [comment]
Thanks, makes sense think my mental model was wrong as I was thinking of it as a domain rather than a URL

TBH tend to use preconnect so hardly use dns-prefetch

prefetch works in Chrome - https://www.webpagetest.org/result/191119_DS_70ced5feee37969e7dc0db3e01d49ddf/1/details/#waterfall_view_step1

But not in Firefox - https://www.webpagetest.org/result/191119_8J_0c4546c443172927a87cf8b87e6d40ea/1/details/#waterfall_view_step1

**Comment by da2x** [comment]
I just published an article about this.
https://www.ctrl.blog/entry/dns-prefetch-preconnect.html

**Pull request merged**
